Repository newzet-dev/mail-server, pull requests merged in 2025-04, with the labels that each got.

#35 Chore: Web및 Swagger Config 추가 및 웹 개발용 CORS open, Swagger JWT 헤더 자동 추가 기능 구현
  build.gradle
  src/main/java/com/newzet/api/config/SwaggerConfig.java
  src/main/java/com/newzet/api/config/WebConfig.java
  src/main/java/com/newzet/api/mail/presentation/MailController.java
Labels: chore

#37 예외 처리 로직 구현
  build.gradle
  src/main/java/com/newzet/api/common/exception/GlobalExceptionHandler.java
  src/main/java/com/newzet/api/common/exception/NewzetException.java
  src/main/java/com/newzet/api/common/logging/LoggingAspect.java
  src/main/java/com/newzet/api/common/response/ResponseCode.java
  src/main/java/com/newzet/api/newsletter/exception/NewsletterNotFoundException.java
Labels: feat

#39 Feat: 객체지향적 JWT 인증 처리 및 커스텀 리졸버/인터셉터 도입
  build.gradle
  src/main/java/com/newzet/api/auth/business/dto/JwtRefreshRequest.java
  src/main/java/com/newzet/api/auth/business/dto/JwtResponse.java
  src/main/java/com/newzet/api/auth/business/service/JwtFactory.java
  src/main/java/com/newzet/api/auth/business/service/JwtService.java
  src/main/java/com/newzet/api/auth/business/validator/JwtValidator.java
  src/main/java/com/newzet/api/auth/domain/AuthUser.java
  src/main/java/com/newzet/api/auth/domain/Token.java
  src/main/java/com/newzet/api/auth/domain/TokenType.java
  src/main/java/com/newzet/api/auth/exception/TokenBadRequestException.java
  src/main/java/com/newzet/api/auth/exception/TokenConflictException.java
  src/main/java/com/newzet/api/auth/exception/TokenExpiredException.java
  src/main/java/com/newzet/api/auth/exception/TokenStolenException.java
  src/main/java/com/newzet/api/auth/infrastructure/RedisRefreshTokenRepository.java
  src/main/java/com/newzet/api/auth/infrastructure/TokenRepository.java
  src/main/java/com/newzet/api/auth/infrastructure/annotation/Login.java
  src/main/java/com/newzet/api/auth/infrastructure/annotation/RequireAuth.java
  src/main/java/com/newzet/api/auth/infrastructure/interceptor/AuthInterceptor.java
  src/main/java/com/newzet/api/auth/infrastructure/resolver/AuthUserArgumentResolver.java
  src/main/java/com/newzet/api/common/response/ResponseCode.java
  src/main/java/com/newzet/api/config/WebConfig.java
  src/main/resources/application.yml
  src/test/java/com/newzet/api/auth/business/service/JwtFactoryTest.java
  src/test/java/com/newzet/api/auth/business/service/JwtServiceTest.java
  src/test/java/com/newzet/api/auth/business/validator/JwtValidatorTest.java
  src/test/java/com/newzet/api/auth/domain/AuthUserTest.java
  src/test/java/com/newzet/api/auth/domain/TokenTest.java
  src/test/java/com/newzet/api/auth/infrastructure/RedisRefreshTokenRepositoryIntegrationTest.java
  src/test/java/com/newzet/api/auth/infrastructure/RedisRefreshTokenRepositoryTest.java
  src/test/java/com/newzet/api/auth/infrastructure/interceptor/AuthInterceptorTest.java
  src/test/java/com/newzet/api/auth/infrastructure/resolver/AuthUserArgumentResolverTest.java
  src/test/java/com/newzet/api/config/JwtTestConfig.java
  src/test/java/com/newzet/api/newsletter/business/NewsletterServiceConcurrencyTest.java
Labels: feat, test

#47 Fix: 리프레쉬 토큰 저장시간의 TTL이 끝난 이후 요청하는 오류 해결
  src/main/java/com/newzet/api/auth/business/validator/JwtValidator.java
  src/main/java/com/newzet/api/auth/infrastructure/RedisRefreshTokenRepository.java
  src/main/java/com/newzet/api/auth/infrastructure/TokenRepository.java
  src/test/java/com/newzet/api/auth/business/validator/JwtValidatorTest.java
  src/test/java/com/newzet/api/auth/infrastructure/RedisRefreshTokenRepositoryIntegrationTest.java
  src/test/java/com/newzet/api/auth/infrastructure/RedisRefreshTokenRepositoryTest.java
Labels: fix

#52 User 도메인 객체 및 Entity의 식별자 자료형 UUID로 변경 및 Auth로직 폴더 구조 맞춤 개선
  src/main/java/com/newzet/api/auth/business/service/JwtFactory.java
  src/main/java/com/newzet/api/auth/business/service/JwtService.java
  src/main/java/com/newzet/api/auth/business/service/TokenRepository.java
  src/main/java/com/newzet/api/auth/business/validator/JwtValidator.java
  src/main/java/com/newzet/api/auth/domain/AuthUser.java
  src/main/java/com/newzet/api/auth/infrastructure/TokenRepository.java
  src/main/java/com/newzet/api/auth/repository/RedisTokenRepositoryImpl.java
  src/main/java/com/newzet/api/subscription/business/service/SubscriptionRepository.java
  src/main/java/com/newzet/api/subscription/repository/repository/SubscriptionJpaRepository.java
  src/main/java/com/newzet/api/subscription/repository/repository/SubscriptionRepositoryImpl.java
  src/main/java/com/newzet/api/user/business/dto/UserEntityDto.java
  src/main/java/com/newzet/api/user/business/service/UserFactory.java
  src/main/java/com/newzet/api/user/domain/ActiveUser.java
  src/main/java/com/newzet/api/user/domain/User.java
  src/main/java/com/newzet/api/user/repository/entity/UserEntity.java
  src/test/java/com/newzet/api/auth/business/service/JwtFactoryTest.java
  src/test/java/com/newzet/api/auth/business/service/JwtServiceTest.java
  src/test/java/com/newzet/api/auth/business/validator/JwtValidatorTest.java
  src/test/java/com/newzet/api/auth/domain/AuthUserTest.java
  src/test/java/com/newzet/api/auth/infrastructure/interceptor/AuthInterceptorTest.java
  src/test/java/com/newzet/api/auth/infrastructure/resolver/AuthUserArgumentResolverTest.java
  src/test/java/com/newzet/api/auth/repository/RedisTokenRepositoryImplIntegrationTest.java
  src/test/java/com/newzet/api/auth/repository/RedisTokenRepositoryImplTest.java
  src/test/java/com/newzet/api/subscription/business/SubscriptionServiceTest.java
  src/test/java/com/newzet/api/subscription/repository/SubscriptionRepositoryImplTest.java
  src/test/java/com/newzet/api/user/business/UserFactoryTest.java
  src/test/java/com/newzet/api/user/domain/ActiveUserTest.java
Labels: refactor

#53 Category API 구현
  src/main/java/com/newzet/api/category/business/CategoryRepository.java
  src/main/java/com/newzet/api/category/business/dto/CategoryEntityDto.java
  src/main/java/com/newzet/api/category/business/service/CategoryService.java
  src/main/java/com/newzet/api/category/controller/CategoryController.java
  src/main/java/com/newzet/api/category/controller/dto/CategoryListResponse.java
  src/main/java/com/newzet/api/category/controller/dto/CategoryResponse.java
  src/main/java/com/newzet/api/category/domain/Category.java
  src/main/java/com/newzet/api/category/repository/CategoryEntity.java
  src/main/java/com/newzet/api/category/repository/CategoryJpaRepository.java
  src/main/java/com/newzet/api/category/repository/CategoryRepositoryImpl.java
  src/main/java/com/newzet/api/category/repository/exception/NoCategoryException.java
  src/main/java/com/newzet/api/common/response/SuccessResponse.java
Labels: feat

#55 User 도메인 Oauth 도입을 위한 구조 조정
  src/main/java/com/newzet/api/subscription/repository/repository/SubscriptionRepositoryImpl.java
  src/main/java/com/newzet/api/user/business/dto/SignupRequest.java
  src/main/java/com/newzet/api/user/business/dto/UniqueMailResponse.java
  src/main/java/com/newzet/api/user/business/dto/UserEntityDto.java
  src/main/java/com/newzet/api/user/business/service/UserFactory.java
  src/main/java/com/newzet/api/user/business/service/UserRepository.java
  src/main/java/com/newzet/api/user/business/service/UserService.java
  src/main/java/com/newzet/api/user/controller/UserController.java
  src/main/java/com/newzet/api/user/domain/ActiveUser.java
  src/main/java/com/newzet/api/user/domain/User.java
  src/main/java/com/newzet/api/user/domain/UserDomain.java
  src/main/java/com/newzet/api/user/exception/InActiveUserException.java
  src/main/java/com/newzet/api/user/exception/NoUserException.java
  src/main/java/com/newzet/api/user/exception/UserEmailDuplicateException.java
  src/main/java/com/newzet/api/user/exception/WithdrawnUserException.java
  src/main/java/com/newzet/api/user/repository/entity/UserEntity.java
  src/main/java/com/newzet/api/user/repository/repository/UserJpaRepository.java
  src/main/java/com/newzet/api/user/repository/repository/UserRepositoryImpl.java
  src/test/java/com/newzet/api/subscription/business/SubscriptionServiceTest.java
  src/test/java/com/newzet/api/subscription/repository/SubscriptionRepositoryImplTest.java
  src/test/java/com/newzet/api/user/business/UserFactoryTest.java
  src/test/java/com/newzet/api/user/business/service/UserServiceTest.java
  src/test/java/com/newzet/api/user/domain/UserDomainTest.java
  src/test/java/com/newzet/api/user/repository/UserRepositoryImplTest.java
Labels: refactor

#58 Refactor: UserEntity단에 toEntityDto 도입
  src/main/java/com/newzet/api/user/repository/entity/UserEntity.java
  src/main/java/com/newzet/api/user/repository/repository/UserRepositoryImpl.java
Labels: refactor

#61 Token 도메인과 repository단의 종속성 제거
  src/main/java/com/newzet/api/auth/business/dto/TokenDTO.java
  src/main/java/com/newzet/api/auth/business/service/JwtService.java
  src/main/java/com/newzet/api/auth/business/service/TokenRepository.java
  src/main/java/com/newzet/api/auth/business/validator/JwtValidator.java
  src/main/java/com/newzet/api/auth/domain/Token.java
  src/main/java/com/newzet/api/auth/repository/RedisTokenRepositoryImpl.java
  src/test/java/com/newzet/api/auth/business/service/JwtServiceTest.java
  src/test/java/com/newzet/api/auth/business/validator/JwtValidatorTest.java
  src/test/java/com/newzet/api/auth/repository/RedisTokenRepositoryImplIntegrationTest.java
  src/test/java/com/newzet/api/auth/repository/RedisTokenRepositoryImplTest.java
Labels: refactor

#56 Redis 및 Caffeine의 eviction, 메모리 관리, 영속성, 리소스 제한 및 자동 재시작 설정
  docker-compose-redis.yml
  src/main/java/com/newzet/api/common/cache/local/LocalCacheUtil.java
  src/main/java/com/newzet/api/config/CaffeineConfig.java
  src/main/java/com/newzet/api/config/RedisConfig.java
  src/test/java/com/newzet/api/common/cache/LocalCacheUtilTest.java
Labels: chore

#63 Newletter API 구현
  src/main/java/com/newzet/api/category/repository/CategoryEntity.java
  src/main/java/com/newzet/api/category/repository/CategoryRepositoryImpl.java
  src/main/java/com/newzet/api/common/util/UuidConverter.java
  src/main/java/com/newzet/api/common/util/exception/UuidConvertFailException.java
  src/main/java/com/newzet/api/newsletter/business/NewsletterRepository.java
  src/main/java/com/newzet/api/newsletter/business/NewsletterService.java
  src/main/java/com/newzet/api/newsletter/business/dto/NewsletterCacheDto.java
  src/main/java/com/newzet/api/newsletter/business/dto/NewsletterEntityDto.java
  src/main/java/com/newzet/api/newsletter/controller/NewsletterController.java
  src/main/java/com/newzet/api/newsletter/controller/dto/NewsletterInfoResponse.java
  src/main/java/com/newzet/api/newsletter/controller/dto/NewsletterListResponse.java
  src/main/java/com/newzet/api/newsletter/controller/dto/NewsletterResponse.java
  src/main/java/com/newzet/api/newsletter/domain/Color.java
  src/main/java/com/newzet/api/newsletter/domain/Newsletter.java
  src/main/java/com/newzet/api/newsletter/repository/NewsletterEntity.java
  src/main/java/com/newzet/api/newsletter/repository/NewsletterJpaRepository.java
  src/main/java/com/newzet/api/newsletter/repository/NewsletterRepositoryImpl.java
  src/main/java/com/newzet/api/newsletter/repository/exception/NoNewsletterException.java
  src/main/java/com/newzet/api/subscription/business/service/SubscriptionRepository.java
  src/main/java/com/newzet/api/subscription/repository/repository/SubscriptionJpaRepository.java
  src/main/java/com/newzet/api/subscription/repository/repository/SubscriptionRepositoryImpl.java
  src/test/java/com/newzet/api/newsletter/business/NewsletterServiceConcurrencyTest.java
  src/test/java/com/newzet/api/newsletter/business/NewsletterServiceTest.java
  src/test/java/com/newzet/api/newsletter/domain/NewsletterTest.java
  src/test/java/com/newzet/api/newsletter/fixture/NewsletterFixture.java
  src/test/java/com/newzet/api/newsletter/repository/NewsletterEntityTest.java
  src/test/java/com/newzet/api/newsletter/repository/NewsletterRepositoryImplTest.java
  src/test/java/com/newzet/api/subscription/business/SubscriptionServiceTest.java
  src/test/java/com/newzet/api/subscription/repository/SubscriptionRepositoryImplTest.java
Labels: feat
