Repository newzet-dev/mail-server, pull requests merged in 2025-08, with the labels that each got.

#104 JAVA 버전 17 -> 21로 업그레이드
  .github/workflows/ci.yml
  .github/workflows/ci_cd.yml
  Dockerfile
  build.gradle
Labels: chore

#110 dev 브랜치용 dev서버 연결 및 CI/CD
  .github/workflows/dev_ci_cd.yml
Labels: feat

#106 AuthUser에 Optional 도입 및 UserTokenResolver 생성
  src/main/java/com/newzet/api/common/auth/annotation/OptionalLogin.java
  src/main/java/com/newzet/api/common/auth/business/AuthTokenProcessor.java
  src/main/java/com/newzet/api/common/auth/business/TokenConverter.java
  src/main/java/com/newzet/api/common/auth/domain/Token.java
  src/main/java/com/newzet/api/common/auth/interceptor/AuthInterceptor.java
  src/main/java/com/newzet/api/common/auth/resolver/AuthUserArgumentResolver.java
  src/main/java/com/newzet/api/newsletter/presentation/controller/NewsletterController.java
  src/test/java/com/newzet/api/common/auth/business/AuthTokenProcessorTest.java
  src/test/java/com/newzet/api/common/auth/business/TokenConverterTest.java
  src/test/java/com/newzet/api/common/auth/business/TokenValidatorTest.java
  src/test/java/com/newzet/api/common/auth/domain/TokenTest.java
  src/test/java/com/newzet/api/common/auth/intercepter/AuthInterceptorTest.java
  src/test/java/com/newzet/api/common/auth/resolver/AuthUserArgumentResolverTest.java
  src/test/java/com/newzet/api/newsletter/presentation/controller/NewsletterControllerTest.java
Labels: refactor

#112 Subscription API 수정
  src/main/java/com/newzet/api/common/auth/business/TokenConverter.java
  src/main/java/com/newzet/api/subscription/business/service/SubscriptionService.java
  src/main/java/com/newzet/api/subscription/jpa/dto/SubscriptionListWithImageProjection.java
  src/main/java/com/newzet/api/subscription/jpa/repository/SubscriptionJpaQueryRepository.java
  src/main/java/com/newzet/api/subscription/jpa/repository/SubscriptionJpaRepository.java
  src/main/java/com/newzet/api/subscription/jpa/repository/SubscriptionRepositoryImpl.java
  src/main/java/com/newzet/api/subscription/presentation/controller/SubscriptionController.java
  src/test/java/com/newzet/api/common/auth/business/TokenConverterTest.java
  src/test/java/com/newzet/api/subscription/jpa/SubscriptionRepositoryImplTest.java
Labels: fix

#114 @RequireAuth 메서드 필요한 부분에 추가
  src/main/java/com/newzet/api/userinfo/presentation/controller/UserinfoController.java
Labels: fix

#103 AWS S3로부터 아티클 본문을 받아오는 로직 기반 구현
  build.gradle
  src/main/java/com/newzet/api/article/business/service/ArticleService.java
  src/main/java/com/newzet/api/article/controller/ArticleController.java
  src/main/java/com/newzet/api/article/orchestrator/ArticleOrchestrator.java
  src/main/java/com/newzet/api/common/s3/S3Service.java
  src/main/java/com/newzet/api/config/s3/S3Config.java
  src/main/resources/application.yml
  src/test/java/com/newzet/api/article/business/ArticleServiceTest.java
  src/test/java/com/newzet/api/article/repository/batch/ArticleRedisBatchProcessorIntegrationTest.java
  src/test/java/com/newzet/api/common/s3/S3ServiceTest.java
  src/test/java/com/newzet/api/config/S3TestConfig.java
  src/test/java/com/newzet/api/newsletter/business/NewsletterServiceConcurrencyTest.java
Labels: feat
